// frontend/src/lib/components/GraphToolbar.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import type { GraphNode, NodeType, NodeStatus } from '$lib/types';

	interface Props {
		onAddNode: () => void;
		onAddGroup: () => void;
		onZoomIn: () => void;
		onZoomOut: () => void;
		onFitView: () => void;
		onRunLayout: () => void;
		onToggleImpact: () => void;
		isImpactActive: boolean;
		nodes: GraphNode[];
		onFocusNode: (nodeId: string) => void;
		onUndo: () => void;
		onRedo: () => void;
		canUndo: boolean;
		canRedo: boolean;
	}

	let {
		onAddNode,
		onAddGroup,
		onZoomIn,
		onZoomOut,
		onFitView,
		onRunLayout,
		onToggleImpact,
		isImpactActive,
		nodes,
		onFocusNode,
		onUndo,
		onRedo,
		canUndo,
		canRedo,
	}: Props = $props();

	const NODE_TYPES: NodeType[] = ['FLOW', 'BRANCH', 'TASK', 'BUG', 'API', 'UI', 'GROUP'];
	const STATUS_OPTIONS: { value: NodeStatus; color: string }[] = [
		{ value: 'PASS', color: '#22c55e' },
		{ value: 'FAIL', color: '#ef4444' },
		{ value: 'IN_PROGRESS', color: '#6366f1' },
		{ value: 'BLOCKED', color: '#f59e0b' },
	];

	let showFilters = $state(false);
	let activeTypeFilter = $state<NodeType | null>(null);
	let activeStatusFilter = $state<NodeStatus | null>(null);

	let showSearch = $state(false);
	let searchQuery = $state('');
	let searchResults = $state<GraphNode[]>([]);
	let searchIndex = $state(0);
	let searchInput: HTMLInputElement | undefined = $state();

	let searchResultsText = $derived(
		searchResults.length > 0
			? `${searchIndex + 1}/${searchResults.length}`
			: searchQuery.length > 0
				? '0/0'
				: '',
	);

	$effect(() => {
		if (!searchQuery) {
			searchResults = [];
			searchIndex = 0;
			return;
		}
		const q = searchQuery.toLowerCase();
		searchResults = nodes.filter(
			(n) => n.title.toLowerCase().includes(q) || (n.description ?? '').toLowerCase().includes(q),
		);
		searchIndex = 0;
		if (searchResults.length > 0) {
			onFocusNode(searchResults[0].id);
		}
	});

	function cycleSearch() {
		if (searchResults.length === 0) return;
		searchIndex = (searchIndex + 1) % searchResults.length;
		onFocusNode(searchResults[searchIndex].id);
	}

	function openSearch() {
		showSearch = true;
		setTimeout(() => searchInput?.focus(), 0);
	}

	function closeSearch() {
		showSearch = false;
		searchQuery = '';
		searchResults = [];
		searchIndex = 0;
	}

	function handleSearchKeydown(e: KeyboardEvent) {
		if (e.key === 'Enter') {
			e.preventDefault();
			cycleSearch();
		} else if (e.key === 'Escape') {
			closeSearch();
		}
	}

	function handleGlobalKeydown(e: KeyboardEvent) {
		if ((e.ctrlKey || e.metaKey) && e.key === 'f') {
			e.preventDefault();
			openSearch();
		}
	}

	onMount(() => {
		window.addEventListener('keydown', handleGlobalKeydown);
	});

	onDestroy(() => {
		window.removeEventListener('keydown', handleGlobalKeydown);
	});
</script>

<div
	class="flex flex-col gap-1 p-2 rounded-lg border shadow-lg"
	style="background: var(--color-surface); border-color: var(--color-border);"
>
	<!-- Main toolbar row -->
	<div class="flex items-center gap-1 flex-wrap">
		<!-- Add buttons -->
		<button
			onclick={onAddNode}
			class="px-2 py-1 rounded text-xs font-medium transition-colors"
			style="background: var(--color-primary); color: white;"
			title="Add Node"
		>
			+ Node
		</button>
		<button
			onclick={onAddGroup}
			class="px-2 py-1 rounded text-xs font-medium transition-colors"
			style="background: var(--color-surface-hover); color: var(--color-text); border: 1px solid var(--color-border);"
			title="Add Group"
		>
			+ Group
		</button>

		<div class="w-px h-5 mx-1" style="background: var(--color-border);"></div>

		<!-- Zoom controls -->
		<button
			onclick={onZoomIn}
			class="w-7 h-7 flex items-center justify-center rounded text-sm font-medium transition-colors"
			style="background: var(--color-surface-hover); color: var(--color-text);"
			title="Zoom In"
		>
			+
		</button>
		<button
			onclick={onZoomOut}
			class="w-7 h-7 flex items-center justify-center rounded text-sm font-medium transition-colors"
			style="background: var(--color-surface-hover); color: var(--color-text);"
			title="Zoom Out"
		>
			−
		</button>
		<button
			onclick={onFitView}
			class="px-2 py-1 rounded text-xs font-medium transition-colors"
			style="background: var(--color-surface-hover); color: var(--color-text);"
			title="Fit View"
		>
			Fit
		</button>
		<button
			onclick={onRunLayout}
			class="px-2 py-1 rounded text-xs font-medium transition-colors"
			style="background: var(--color-surface-hover); color: var(--color-text);"
			title="Auto Layout"
		>
			Layout
		</button>

		<div class="w-px h-5 mx-1" style="background: var(--color-border);"></div>

		<!-- Undo/Redo -->
		<button
			onclick={onUndo}
			disabled={!canUndo}
			class="w-7 h-7 flex items-center justify-center rounded text-sm transition-colors"
			style="background: var(--color-surface-hover); color: {canUndo ? 'var(--color-text)' : 'var(--color-text-muted)'}; opacity: {canUndo ? '1' : '0.5'};"
			title="Undo (Ctrl+Z)"
		>
			↩
		</button>
		<button
			onclick={onRedo}
			disabled={!canRedo}
			class="w-7 h-7 flex items-center justify-center rounded text-sm transition-colors"
			style="background: var(--color-surface-hover); color: {canRedo ? 'var(--color-text)' : 'var(--color-text-muted)'}; opacity: {canRedo ? '1' : '0.5'};"
			title="Redo (Ctrl+Y)"
		>
			↪
		</button>

		<div class="w-px h-5 mx-1" style="background: var(--color-border);"></div>

		<!-- Filter toggle -->
		<button
			onclick={() => (showFilters = !showFilters)}
			class="px-2 py-1 rounded text-xs font-medium transition-colors"
			style="background: {showFilters ? 'var(--color-primary)' : 'var(--color-surface-hover)'}; color: {showFilters ? 'white' : 'var(--color-text)'};"
			title="Toggle Filters"
		>
			Filter {activeTypeFilter || activeStatusFilter ? '●' : ''}
		</button>

		<!-- Search -->
		{#if showSearch}
			<div class="flex items-center gap-1">
				<input
					bind:this={searchInput}
					bind:value={searchQuery}
					onkeydown={handleSearchKeydown}
					placeholder="Search nodes..."
					class="px-2 py-1 rounded text-xs outline-none"
					style="background: var(--color-bg); color: var(--color-text); border: 1px solid var(--color-primary); width: 150px;"
				/>
				{#if searchResultsText}
					<span class="text-xs" style="color: var(--color-text-muted);">{searchResultsText}</span>
				{/if}
				<button
					onclick={closeSearch}
					class="w-5 h-5 flex items-center justify-center rounded text-xs"
					style="color: var(--color-text-muted);"
					title="Close Search (Esc)"
				>
					✕
				</button>
			</div>
		{:else}
			<button
				onclick={openSearch}
				class="px-2 py-1 rounded text-xs font-medium transition-colors"
				style="background: var(--color-surface-hover); color: var(--color-text-muted);"
				title="Search (Ctrl+F)"
			>
				Search
			</button>
		{/if}

		<!-- Impact Mode -->
		<button
			onclick={onToggleImpact}
			class="px-2 py-1 rounded text-xs font-medium transition-colors"
			style="background: {isImpactActive ? '#f59e0b' : 'var(--color-surface-hover)'}; color: {isImpactActive ? '#000' : 'var(--color-text)'};"
			title="Toggle Impact Mode"
		>
			Impact
		</button>
	</div>

	<!-- Filter bar -->
	{#if showFilters}
		<div
			class="flex flex-col gap-1 pt-1 mt-1 border-t"
			style="border-color: var(--color-border);"
		>
			<!-- Node type filters -->
			<div class="flex items-center gap-1 flex-wrap">
				<span class="text-xs mr-1" style="color: var(--color-text-muted);">Type:</span>
				{#each NODE_TYPES as type}
					<button
						onclick={() => (activeTypeFilter = activeTypeFilter === type ? null : type)}
						class="px-2 py-0.5 rounded text-xs font-medium transition-colors"
						style="background: {activeTypeFilter === type ? 'var(--color-primary)' : 'var(--color-bg)'}; color: {activeTypeFilter === type ? 'white' : 'var(--color-text-muted)'}; border: 1px solid var(--color-border);"
					>
						{type}
					</button>
				{/each}
			</div>
			<!-- Status filters -->
			<div class="flex items-center gap-1 flex-wrap">
				<span class="text-xs mr-1" style="color: var(--color-text-muted);">Status:</span>
				{#each STATUS_OPTIONS as opt}
					<button
						onclick={() => (activeStatusFilter = activeStatusFilter === opt.value ? null : opt.value)}
						class="px-2 py-0.5 rounded text-xs font-medium transition-colors flex items-center gap-1"
						style="background: {activeStatusFilter === opt.value ? opt.color + '33' : 'var(--color-bg)'}; color: {activeStatusFilter === opt.value ? opt.color : 'var(--color-text-muted)'}; border: 1px solid {activeStatusFilter === opt.value ? opt.color : 'var(--color-border)'};"
					>
						<span
							class="w-2 h-2 rounded-full inline-block"
							style="background: {opt.color};"
						></span>
						{opt.value}
					</button>
				{/each}
			</div>
		</div>
	{/if}
</div>

// src/components/graph/GraphToolbar.tsx
'use client';

import { useState, useRef, useEffect } from 'react';
import {
  Plus,
  ZoomIn,
  ZoomOut,
  Maximize,
  LayoutGrid,
  AlertTriangle,
  X,
  Search,
  Undo2,
  Redo2,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { NODE_TYPES, type NodeType, NODE_STATUSES, type NodeStatus } from '@/types/graph';
import type { GraphNode } from '@/types/graph';
import { useGraphStore } from '@/stores/useGraphStore';

interface GraphToolbarProps {
  onAddNode: () => void;
  onAddGroup: () => void;
  onZoomIn: () => void;
  onZoomOut: () => void;
  onFitView: () => void;
  onRunLayout: () => void;
  onToggleImpact: () => void;
  isImpactActive: boolean;
  nodes?: GraphNode[];
  onFocusNode?: (nodeId: string) => void;
  onUndo?: () => void;
  onRedo?: () => void;
  canUndo?: boolean;
  canRedo?: boolean;
}

const TYPE_LABELS: Record<NodeType, string> = {
  FLOW: 'Flow',
  BRANCH: 'Branch',
  TASK: 'Task',
  BUG: 'Bug',
  API: 'API',
  UI: 'UI',
  GROUP: 'Group',
};

const STATUS_LABELS: Record<NodeStatus, string> = {
  PASS: 'Pass',
  FAIL: 'Fail',
  IN_PROGRESS: 'In Progress',
  BLOCKED: 'Blocked',
};

const STATUS_COLORS: Record<NodeStatus, string> = {
  PASS: 'bg-green-100 text-green-700 border-green-300',
  FAIL: 'bg-red-100 text-red-700 border-red-300',
  IN_PROGRESS: 'bg-yellow-100 text-yellow-700 border-yellow-300',
  BLOCKED: 'bg-gray-100 text-gray-600 border-gray-300',
};

export function GraphToolbar({
  onAddNode,
  onAddGroup,
  onZoomIn,
  onZoomOut,
  onFitView,
  onRunLayout,
  onToggleImpact,
  isImpactActive,
  nodes = [],
  onFocusNode,
  onUndo,
  onRedo,
  canUndo = false,
  canRedo = false,
}: GraphToolbarProps) {
  const { activeNodeTypeFilters, activeStatusFilters, setNodeTypeFilter, setStatusFilter } =
    useGraphStore();
  const [showFilters, setShowFilters] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [searchIndex, setSearchIndex] = useState(0);
  const searchInputRef = useRef<HTMLInputElement>(null);

  const searchResults = searchQuery.trim()
    ? nodes.filter((n) => n.title.toLowerCase().includes(searchQuery.toLowerCase()))
    : [];

  // Ctrl+F shortcut
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if ((e.ctrlKey || e.metaKey) && e.key === 'f') {
        e.preventDefault();
        setSearchOpen(true);
        setTimeout(() => searchInputRef.current?.focus(), 50);
      }
      if (e.key === 'Escape' && searchOpen) {
        setSearchOpen(false);
        setSearchQuery('');
        setSearchIndex(0);
      }
    }
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [searchOpen]);

  function handleSearchSubmit() {
    if (searchResults.length === 0) return;
    const idx = searchIndex % searchResults.length;
    const target = searchResults[idx];
    if (!target) return;
    onFocusNode?.(target.id);
    setSearchIndex(idx + 1);
  }

  function toggleTypeFilter(type: NodeType) {
    if (activeNodeTypeFilters.includes(type)) {
      setNodeTypeFilter(activeNodeTypeFilters.filter((t) => t !== type));
    } else {
      setNodeTypeFilter([...activeNodeTypeFilters, type]);
    }
  }

  function toggleStatusFilter(status: NodeStatus) {
    if (activeStatusFilters.includes(status)) {
      setStatusFilter(activeStatusFilters.filter((s) => s !== status));
    } else {
      setStatusFilter([...activeStatusFilters, status]);
    }
  }

  return (
    <div className="flex flex-col gap-2 border-b border-gray-200 bg-white px-4 py-2">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-1">
          <button
            onClick={onAddNode}
            className="flex items-center gap-1.5 rounded-lg bg-thask-primary px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-600"
          >
            <Plus className="h-4 w-4" />
            Add Node
          </button>
          <button
            onClick={onAddGroup}
            className="flex items-center gap-1.5 rounded-lg border border-gray-300 px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50"
          >
            <Plus className="h-4 w-4" />
            Add Group
          </button>

          <div className="mx-2 h-6 w-px bg-gray-200" />

          <button onClick={onZoomIn} className="rounded-lg p-1.5 text-gray-500 hover:bg-gray-100" title="Zoom In">
            <ZoomIn className="h-4 w-4" />
          </button>
          <button onClick={onZoomOut} className="rounded-lg p-1.5 text-gray-500 hover:bg-gray-100" title="Zoom Out">
            <ZoomOut className="h-4 w-4" />
          </button>
          <button onClick={onFitView} className="rounded-lg p-1.5 text-gray-500 hover:bg-gray-100" title="Fit to View">
            <Maximize className="h-4 w-4" />
          </button>
          <button onClick={onRunLayout} className="rounded-lg p-1.5 text-gray-500 hover:bg-gray-100" title="Re-run Layout">
            <LayoutGrid className="h-4 w-4" />
          </button>

          <div className="mx-2 h-6 w-px bg-gray-200" />

          <button
            onClick={onUndo}
            disabled={!canUndo}
            className="rounded-lg p-1.5 text-gray-500 hover:bg-gray-100 disabled:opacity-30 disabled:cursor-not-allowed"
            title="Undo (Ctrl+Z)"
          >
            <Undo2 className="h-4 w-4" />
          </button>
          <button
            onClick={onRedo}
            disabled={!canRedo}
            className="rounded-lg p-1.5 text-gray-500 hover:bg-gray-100 disabled:opacity-30 disabled:cursor-not-allowed"
            title="Redo (Ctrl+Shift+Z)"
          >
            <Redo2 className="h-4 w-4" />
          </button>

          <div className="mx-2 h-6 w-px bg-gray-200" />

          <button
            onClick={() => setShowFilters(!showFilters)}
            className={cn(
              'rounded-lg px-3 py-1.5 text-sm font-medium transition-colors',
              showFilters || activeNodeTypeFilters.length > 0 || activeStatusFilters.length > 0
                ? 'bg-blue-50 text-thask-primary'
                : 'text-gray-600 hover:bg-gray-100',
            )}
          >
            Filters
            {(activeNodeTypeFilters.length > 0 || activeStatusFilters.length > 0) && (
              <span className="ml-1.5 inline-flex h-5 w-5 items-center justify-center rounded-full bg-thask-primary text-xs text-white">
                {activeNodeTypeFilters.length + activeStatusFilters.length}
              </span>
            )}
          </button>

          <div className="mx-2 h-6 w-px bg-gray-200" />

          {searchOpen ? (
            <div className="relative flex items-center gap-1">
              <Search className="h-4 w-4 text-gray-400" />
              <input
                ref={searchInputRef}
                type="text"
                value={searchQuery}
                onChange={(e) => { setSearchQuery(e.target.value); setSearchIndex(0); }}
                onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); handleSearchSubmit(); } }}
                placeholder="Search nodes..."
                className="w-44 rounded-lg border border-gray-300 px-2 py-1 text-sm focus:border-thask-primary focus:outline-none focus:ring-1 focus:ring-thask-primary/30"
                autoFocus
              />
              {searchQuery && (
                <span className="text-xs text-gray-400">
                  {searchResults.length > 0 ? `${(searchIndex % searchResults.length) + 1}/${searchResults.length}` : '0'}
                </span>
              )}
              <button
                onClick={() => { setSearchOpen(false); setSearchQuery(''); setSearchIndex(0); }}
                className="rounded p-0.5 text-gray-400 hover:bg-gray-100 hover:text-gray-600"
              >
                <X className="h-3.5 w-3.5" />
              </button>
              {searchQuery && searchResults.length > 0 && (
                <div className="absolute left-0 top-full z-50 mt-1 max-h-48 w-64 overflow-y-auto rounded-lg border border-gray-200 bg-white shadow-lg">
                  {searchResults.map((node, i) => (
                    <button
                      key={node.id}
                      onClick={() => { onFocusNode?.(node.id); setSearchIndex(i + 1); }}
                      className={cn(
                        'flex w-full items-center gap-2 px-3 py-1.5 text-left text-xs hover:bg-gray-50',
                        i === (searchIndex % searchResults.length) && 'bg-blue-50',
                      )}
                    >
                      <span className="rounded bg-slate-200 px-1.5 py-0.5 text-[10px] font-medium text-slate-600">
                        {node.type}
                      </span>
                      <span className="truncate text-gray-700">{node.title}</span>
                    </button>
                  ))}
                </div>
              )}
            </div>
          ) : (
            <button
              onClick={() => { setSearchOpen(true); setTimeout(() => searchInputRef.current?.focus(), 50); }}
              className="rounded-lg p-1.5 text-gray-500 hover:bg-gray-100"
              title="Search (Ctrl+F)"
            >
              <Search className="h-4 w-4" />
            </button>
          )}
        </div>

        <button
          onClick={onToggleImpact}
          className={cn(
            'flex items-center gap-2 rounded-lg px-4 py-1.5 text-sm font-medium transition-all',
            isImpactActive
              ? 'bg-orange-500 text-white shadow-md hover:bg-orange-600'
              : 'border border-orange-300 bg-orange-50 text-orange-700 hover:bg-orange-100',
          )}
        >
          {isImpactActive ? <X className="h-4 w-4" /> : <AlertTriangle className="h-4 w-4" />}
          {isImpactActive ? 'Exit Impact Mode' : 'View Change Impact'}
        </button>
      </div>

      {showFilters && (
        <div className="flex flex-wrap items-center gap-2 pb-1">
          <span className="text-xs font-medium text-gray-500">Type:</span>
          {NODE_TYPES.map((type) => (
            <button
              key={type}
              onClick={() => toggleTypeFilter(type)}
              className={cn(
                'rounded-full border px-2.5 py-0.5 text-xs font-medium transition-colors',
                activeNodeTypeFilters.includes(type)
                  ? 'border-thask-primary bg-blue-50 text-thask-primary'
                  : 'border-gray-200 text-gray-500 hover:border-gray-300',
              )}
            >
              {TYPE_LABELS[type]}
            </button>
          ))}

          <div className="mx-1 h-4 w-px bg-gray-200" />

          <span className="text-xs font-medium text-gray-500">Status:</span>
          {NODE_STATUSES.map((status) => (
            <button
              key={status}
              onClick={() => toggleStatusFilter(status)}
              className={cn(
                'rounded-full border px-2.5 py-0.5 text-xs font-medium transition-colors',
                activeStatusFilters.includes(status)
                  ? STATUS_COLORS[status]
                  : 'border-gray-200 text-gray-500 hover:border-gray-300',
              )}
            >
              {STATUS_LABELS[status]}
            </button>
          ))}

          {(activeNodeTypeFilters.length > 0 || activeStatusFilters.length > 0) && (
            <button
              onClick={() => {
                setNodeTypeFilter([]);
                setStatusFilter([]);
              }}
              className="ml-2 text-xs text-gray-400 hover:text-gray-600"
            >
              Clear all
            </button>
          )}
        </div>
      )}
    </div>
  );
}
