// src/components/graph/AddNodeModal.tsx
'use client';

import { useState } from 'react';
import { X } from 'lucide-react';
import type { NodeType } from '@/types/graph';

interface AddNodeModalProps {
  onSubmit: (data: { title: string; type: NodeType }) => void;
  onClose: () => void;
}

const MODAL_NODE_TYPES = ['FLOW', 'BRANCH', 'TASK', 'BUG', 'API', 'UI'] as const;

const TYPE_LABELS: Record<NodeType, string> = {
  FLOW: 'Flow',
  BRANCH: 'Branch',
  TASK: 'Task',
  BUG: 'Bug',
  API: 'API',
  UI: 'UI',
  GROUP: 'Group',
};

const TYPE_DESCRIPTIONS: Record<NodeType, string> = {
  FLOW: 'A feature flow or user journey',
  BRANCH: 'A decision branch or business rule',
  TASK: 'A development task or work item',
  BUG: 'A bug report or known issue',
  API: 'An API endpoint or integration',
  UI: 'A UI component or screen',
  GROUP: 'A group container for related nodes',
};

export function AddNodeModal({ onSubmit, onClose }: AddNodeModalProps) {
  const [title, setTitle] = useState('');
  const [type, setType] = useState<NodeType>('TASK');

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!title.trim()) return;
    onSubmit({ title: title.trim(), type });
    onClose();
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
      <div className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl">
        <div className="mb-4 flex items-center justify-between">
          <h2 className="text-lg font-semibold text-gray-900">Add Node</h2>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
            <X className="h-5 w-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700">Title</label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              required
              autoFocus
              className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-thask-primary focus:outline-none focus:ring-2 focus:ring-thask-primary/20"
              placeholder="Enter node title"
            />
          </div>

          <div>
            <label className="mb-2 block text-sm font-medium text-gray-700">Type</label>
            <div className="grid grid-cols-3 gap-2">
              {MODAL_NODE_TYPES.map((t) => (
                <button
                  key={t}
                  type="button"
                  onClick={() => setType(t)}
                  className={`rounded-lg border p-2 text-center transition-colors ${
                    type === t
                      ? 'border-thask-primary bg-blue-50 text-thask-primary'
                      : 'border-gray-200 text-gray-600 hover:border-gray-300'
                  }`}
                >
                  <div className="text-sm font-medium">{TYPE_LABELS[t]}</div>
                  <div className="mt-0.5 text-[10px] text-gray-400">{TYPE_DESCRIPTIONS[t]}</div>
                </button>
              ))}
            </div>
          </div>

          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={onClose}
              className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="rounded-lg bg-thask-primary px-4 py-2 text-sm font-medium text-white hover:bg-blue-600"
            >
              Add Node
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

// frontend/src/lib/components/AddNodeModal.svelte
<script lang="ts">
	import type { NodeType } from '$lib/types';

	interface Props {
		onsubmit: (data: { title: string; type: NodeType }) => void;
		onclose: () => void;
	}

	let { onsubmit, onclose }: Props = $props();

	const NODE_TYPES: NodeType[] = ['FLOW', 'BRANCH', 'TASK', 'BUG', 'API', 'UI'];

	const TYPE_COLORS: Record<NodeType, string> = {
		FLOW: '#6366f1',
		BRANCH: '#8b5cf6',
		TASK: '#3b82f6',
		BUG: '#ef4444',
		API: '#22c55e',
		UI: '#f59e0b',
		GROUP: '#64748b',
	};

	let title = $state('');
	let selectedType = $state<NodeType>('TASK');

	function handleSubmit() {
		const trimmed = title.trim();
		if (!trimmed) return;
		onsubmit({ title: trimmed, type: selectedType });
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			onclose();
		}
	}

	function handleOverlayClick(e: MouseEvent) {
		if (e.target === e.currentTarget) {
			onclose();
		}
	}
</script>

<svelte:window onkeydown={handleKeydown} />

<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
<div
	class="fixed inset-0 flex items-center justify-center z-50"
	style="background: rgba(0,0,0,0.6);"
	onclick={handleOverlayClick}
>
	<div
		class="w-full max-w-md rounded-xl p-6 shadow-2xl flex flex-col gap-4"
		style="background: var(--color-surface); border: 1px solid var(--color-border);"
	>
		<h2 class="text-lg font-semibold" style="color: var(--color-text);">Add Node</h2>

		<!-- Title input -->
		<div class="flex flex-col gap-1">
			<label class="text-sm font-medium" style="color: var(--color-text-muted);" for="node-title">
				Title <span style="color: var(--color-danger);">*</span>
			</label>
			<input
				id="node-title"
				bind:value={title}
				placeholder="Enter node title..."
				class="px-3 py-2 rounded-lg text-sm outline-none"
				style="background: var(--color-bg); color: var(--color-text); border: 1px solid var(--color-border);"
				onkeydown={(e) => { if (e.key === 'Enter') handleSubmit(); }}
			/>
		</div>

		<!-- Type selection -->
		<div class="flex flex-col gap-2">
			<span class="text-sm font-medium" style="color: var(--color-text-muted);">Type</span>
			<div class="grid grid-cols-3 gap-2">
				{#each NODE_TYPES as type}
					<button
						onclick={() => (selectedType = type)}
						class="py-2 px-3 rounded-lg text-sm font-medium transition-all flex items-center gap-2"
						style="
							background: {selectedType === type ? TYPE_COLORS[type] + '22' : 'var(--color-bg)'};
							color: {selectedType === type ? TYPE_COLORS[type] : 'var(--color-text-muted)'};
							border: 1.5px solid {selectedType === type ? TYPE_COLORS[type] : 'var(--color-border)'};
						"
					>
						<span
							class="w-2.5 h-2.5 rounded-full flex-shrink-0"
							style="background: {TYPE_COLORS[type]};"
						></span>
						{type}
					</button>
				{/each}
			</div>
		</div>

		<!-- Actions -->
		<div class="flex justify-end gap-2 pt-1">
			<button
				onclick={onclose}
				class="px-4 py-2 rounded-lg text-sm font-medium transition-colors"
				style="background: var(--color-bg); color: var(--color-text-muted); border: 1px solid var(--color-border);"
			>
				Cancel
			</button>
			<button
				onclick={handleSubmit}
				disabled={!title.trim()}
				class="px-4 py-2 rounded-lg text-sm font-medium transition-colors"
				style="background: {title.trim() ? 'var(--color-primary)' : 'var(--color-surface-hover)'}; color: {title.trim() ? 'white' : 'var(--color-text-muted)'}; opacity: {title.trim() ? '1' : '0.6'};"
			>
				Create Node
			</button>
		</div>
	</div>
</div>
