// src/components/graph/EdgeColorPopover.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import type { EdgeType } from '@/types/graph';

const EDGE_TYPE_OPTIONS: { value: EdgeType; label: string; color: string }[] = [
  { value: 'depends_on', label: 'Depends On', color: '#f97316' },
  { value: 'blocks', label: 'Blocks', color: '#ef4444' },
  { value: 'related', label: 'Related', color: '#6b7280' },
  { value: 'parent_child', label: 'Parent / Child', color: '#8b5cf6' },
  { value: 'triggers', label: 'Triggers', color: '#3b82f6' },
];

interface EdgeColorPopoverProps {
  position: { x: number; y: number };
  currentLabel?: string;
  onSelect: (edgeType: EdgeType) => void;
  onUpdateLabel?: (label: string) => void;
  onDelete: () => void;
  onCancel: () => void;
}

export function EdgeColorPopover({ position, currentLabel = '', onSelect, onUpdateLabel, onDelete, onCancel }: EdgeColorPopoverProps) {
  const ref = useRef<HTMLDivElement>(null);
  const [label, setLabel] = useState(currentLabel);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  function handleLabelChange(value: string) {
    setLabel(value);
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      onUpdateLabel?.(value);
    }, 400);
  }

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) {
        onCancel();
      }
    }

    function handleEsc(e: KeyboardEvent) {
      if (e.key === 'Escape') onCancel();
    }

    document.addEventListener('mousedown', handleClickOutside);
    document.addEventListener('keydown', handleEsc);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
      document.removeEventListener('keydown', handleEsc);
    };
  }, [onCancel]);

  return (
    <div
      ref={ref}
      className="fixed z-50 w-48 rounded-lg border border-gray-200 bg-white py-1 shadow-lg"
      style={{ left: position.x, top: position.y }}
    >
      <div className="px-3 py-1.5">
        <input
          type="text"
          value={label}
          onChange={(e) => handleLabelChange(e.target.value)}
          placeholder="Edge label..."
          className="w-full rounded border border-gray-200 px-2 py-1 text-xs focus:border-thask-primary focus:outline-none"
          onClick={(e) => e.stopPropagation()}
        />
      </div>
      <div className="mx-2 border-t border-gray-200" />
      <div className="px-3 py-1.5 text-xs font-semibold text-gray-400 uppercase">
        Edge Type
      </div>
      {EDGE_TYPE_OPTIONS.map((opt) => (
        <button
          key={opt.value}
          onClick={() => onSelect(opt.value)}
          className="flex w-full items-center gap-2.5 px-3 py-2 text-sm text-gray-700 hover:bg-gray-50"
        >
          <span
            className="inline-block h-3 w-3 rounded-full"
            style={{ backgroundColor: opt.color }}
          />
          {opt.label}
        </button>
      ))}
      <div className="mx-2 my-1 border-t border-gray-200" />
      <button
        onClick={onDelete}
        className="flex w-full items-center gap-2.5 px-3 py-2 text-sm text-red-600 hover:bg-red-50"
      >
        <svg className="h-3 w-3" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5">
          <path d="M2 3h8M4.5 3V2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5v1M9 3v6.5a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V3" />
        </svg>
        Delete
      </button>
    </div>
  );
}

// frontend/src/lib/components/EdgeColorPopover.svelte
<script lang="ts">
	import type { EdgeType } from '$lib/types';

	interface Props {
		position: { x: number; y: number };
		currentLabel: string;
		onselect: (edgeType: EdgeType) => void;
		onupdatelabel: (label: string) => void;
		ondelete: () => void;
		oncancel: () => void;
	}

	let { position, currentLabel, onselect, onupdatelabel, ondelete, oncancel }: Props = $props();

	const EDGE_TYPES: { value: EdgeType; label: string; color: string }[] = [
		{ value: 'depends_on', label: 'Depends On', color: '#6366f1' },
		{ value: 'blocks', label: 'Blocks', color: '#ef4444' },
		{ value: 'related', label: 'Related', color: '#64748b' },
		{ value: 'parent_child', label: 'Parent / Child', color: '#22c55e' },
		{ value: 'triggers', label: 'Triggers', color: '#f59e0b' },
	];

	let label = $state('');
	let debounceTimer: ReturnType<typeof setTimeout> | null = null;

	$effect(() => {
		label = currentLabel;
	});

	function handleLabelInput() {
		if (debounceTimer) clearTimeout(debounceTimer);
		debounceTimer = setTimeout(() => {
			onupdatelabel(label);
		}, 400);
	}

	function handleOverlayClick(e: MouseEvent) {
		if (e.target === e.currentTarget) {
			oncancel();
		}
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			oncancel();
		}
	}
</script>

<svelte:window onkeydown={handleKeydown} />

<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
<div
	class="fixed inset-0 z-40"
	style="background: transparent;"
	onclick={handleOverlayClick}
>
	<div
		class="absolute rounded-xl p-4 shadow-2xl flex flex-col gap-3 w-56"
		style="
			left: {position.x}px;
			top: {position.y}px;
			background: var(--color-surface);
			border: 1px solid var(--color-border);
		"
		role="dialog"
		aria-label="Edge options"
	>
		<!-- Label input -->
		<div class="flex flex-col gap-1">
			<label class="text-xs font-medium" style="color: var(--color-text-muted);" for="edge-label">
				Label
			</label>
			<input
				id="edge-label"
				bind:value={label}
				oninput={handleLabelInput}
				placeholder="Edge label..."
				class="px-2 py-1.5 rounded text-xs outline-none"
				style="background: var(--color-bg); color: var(--color-text); border: 1px solid var(--color-border);"
			/>
		</div>

		<!-- Edge type selection -->
		<div class="flex flex-col gap-1">
			<span class="text-xs font-medium" style="color: var(--color-text-muted);">Type</span>
			<div class="flex flex-col gap-1">
				{#each EDGE_TYPES as et}
					<button
						onclick={() => onselect(et.value)}
						class="flex items-center gap-2 px-2 py-1.5 rounded text-xs font-medium text-left transition-colors"
						style="background: var(--color-bg); color: var(--color-text);"
						onmouseenter={(e) => {
							(e.currentTarget as HTMLElement).style.background = 'var(--color-surface-hover)';
						}}
						onmouseleave={(e) => {
							(e.currentTarget as HTMLElement).style.background = 'var(--color-bg)';
						}}
					>
						<span
							class="w-3 h-3 rounded-full flex-shrink-0"
							style="background: {et.color};"
						></span>
						{et.label}
					</button>
				{/each}
			</div>
		</div>

		<!-- Delete button -->
		<button
			onclick={ondelete}
			class="mt-1 px-3 py-1.5 rounded text-xs font-medium transition-colors"
			style="background: #ef444422; color: #ef4444; border: 1px solid #ef444444;"
			onmouseenter={(e) => {
				(e.currentTarget as HTMLElement).style.background = '#ef444433';
			}}
			onmouseleave={(e) => {
				(e.currentTarget as HTMLElement).style.background = '#ef444422';
			}}
		>
			Delete Edge
		</button>
	</div>
</div>
